/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
              "surface-container-highest": "#e4e1ee",
              "tertiary-fixed": "#ffdbcc",
              "surface-container-low": "#f5f2ff",
              "on-tertiary-fixed": "#351000",
              "tertiary": "#7e3000",
              "on-surface-variant": "#464555",
              "surface-bright": "#fcf8ff",
              "on-primary-fixed-variant": "#3323cc",
              "secondary-container": "#39b8fd",
              "surface-tint": "#4d44e3",
              "on-secondary-container": "#004666",
              "surface": "#fcf8ff",
              "on-primary-fixed": "#0f0069",
              "surface-container": "#f0ecf9",
              "on-primary": "#ffffff",
              "inverse-primary": "#c3c0ff",
              "on-secondary-fixed": "#001e2f",
              "error": "#ba1a1a",
              "on-secondary": "#ffffff",
              "secondary-fixed": "#c9e6ff",
              "secondary": "#006591",
              "surface-variant": "#e4e1ee",
              "on-secondary-fixed-variant": "#004c6e",
              "on-error": "#ffffff",
              "on-error-container": "#93000a",
              "on-tertiary": "#ffffff",
              "on-background": "#1b1b24",
              "surface-container-high": "#eae6f4",
              "outline-variant": "#c7c4d8",
              "outline": "#777587",
              "inverse-on-surface": "#f3effc",
              "primary-fixed": "#e2dfff",
              "error-container": "#ffdad6",
              "secondary-fixed-dim": "#89ceff",
              "on-tertiary-fixed-variant": "#7b2f00",
              "surface-container-lowest": "#ffffff",
              "on-tertiary-container": "#ffd2be",
              "tertiary-container": "#a44100",
              "primary-fixed-dim": "#c3c0ff",
              "inverse-surface": "#302f39",
              "tertiary-fixed-dim": "#ffb695",
              "primary-container": "#4f46e5",
              "on-primary-container": "#dad7ff",
              "surface-dim": "#dcd8e5",
              "background": "#fcf8ff",
              "primary": "#3525cd",
              "on-surface": "#1b1b24"
      },
      "borderRadius": {
              "DEFAULT": "0.25rem",
              "lg": "0.5rem",
              "xl": "0.75rem",
              "full": "9999px"
      },
      "spacing": {
              "sm": "12px",
              "lg": "40px",
              "gutter": "24px",
              "base": "8px",
              "container-max": "1440px",
              "md": "24px",
              "xs": "4px",
              "xl": "64px"
      },
      "fontFamily": {
              "plus": ["Plus Jakarta Sans", "sans-serif"],
              "body-lg": ["Plus Jakarta Sans"],
              "label-caps": ["Plus Jakarta Sans"],
              "body-md": ["Plus Jakarta Sans"],
              "h1": ["Plus Jakarta Sans"],
              "h2": ["Plus Jakarta Sans"],
              "data-tabular": ["Plus Jakarta Sans"]
      },
      "fontSize": {
              "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
              "label-caps": ["12px", {"lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "700"}],
              "body-md": ["16px", {"lineHeight": "1.5", "fontWeight": "400"}],
              "h1": ["36px", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700"}],
              "h2": ["24px", {"lineHeight": "1.3", "letterSpacing": "-0.01em", "fontWeight": "600"}],
              "data-tabular": ["14px", {"lineHeight": "1.4", "fontWeight": "500"}]
      }
    },
  },
  plugins: [],
}
